export const examResultsConst = {
    uploadExamResultsModelConst: {
        uploadExamResultsModelTitle: 'رفع نتائج الاختبار',
        examSelectLabel: 'اختر الاختبار',
        examSelectPlaceholder: 'اختر الاختبار',
        examSelectError: 'يرجى اختيار الاختبار',
        fileUploadTitle: 'رفع ملف النتائج',
        fileUploadHint: 'يدعم الملفات: Excel (.xlsx, .xls) أو CSV',
        manualEntryTitle: 'إدخال النتائج يدوياً',
        addResultButton: 'إضافة نتيجة',
        studentNameLabel: 'اسم الطالب',
        studentNamePlaceholder: 'اسم الطالب',
        studentIdLabel: 'رقم الطالب',
        studentIdPlaceholder: 'رقم الطالب',
        scoreLabel: 'الدرجة',
        scorePlaceholder: 'الدرجة',
        notesLabel: 'الملاحظات',
        notesPlaceholder: 'ملاحظات (اختياري)',
        examDateLabel: 'تاريخ الاختبار',
        summaryTitle: 'ملخص النتائج:',
        resultsCountText: 'عدد النتائج المضافة:',
        submitButton: 'رفع النتائج',
        cancelButton: 'إلغاء',
        noResultsError: 'يرجى إضافة نتائج اختبار واحدة على الأقل'
    },
    viewExamResultsModelConst: {
        viewExamResultsModelTitle: 'تفاصيل نتيجة الاختبار',
        studentInfoTitle: 'معلومات الطالب',
        studentIdLabel: 'رقم الطالب:',
        examInfoTitle: 'معلومات الاختبار',
        examNameLabel: 'اسم الاختبار',
        examDateLabel: 'تاريخ الاختبار',
        uploadDateLabel: 'تاريخ الرفع',
        statusLabel: 'الحالة',
        passStatus: 'ناجح',
        failStatus: 'راسب',
        scoreDetailsTitle: 'تفاصيل الدرجة',
        totalScoreLabel: 'الدرجة الكلية:',
        requiredScoreLabel: 'الدرجة المطلوبة للنجاح:',
        differenceLabel: 'الفرق:',
        additionalDetailsTitle: 'تفاصيل إضافية',
        notesTitle: 'ملاحظات',
        sectionsTitle: 'تفصيل الأقسام',
        timeInfoTitle: 'معلومات الوقت',
        timeSpentLabel: 'الوقت المستغرق',
        totalTimeLabel: 'الوقت المحدد',
        closeButton: 'إغلاق'
    },
    examResultsTableConst: {
        studentNameColumn: 'اسم الطالب',
        examNameColumn: 'اسم الاختبار',
        scoreColumn: 'الدرجة',
        statusColumn: 'الحالة',
        examDateColumn: 'تاريخ الاختبار',
        uploadDateColumn: 'تاريخ الرفع',
        actionsColumn: 'الإجراءات',
        viewDetailsTitle: 'عرض التفاصيل',
        downloadResultTitle: 'تحميل النتيجة',
        deleteResultTitle: 'حذف النتيجة'
    },
    examResultsPageConst: {
        pageTitle: 'نتائج الاختبارات',
        uploadButton: 'رفع نتائج اختبار',
        examFilterLabel: 'اختر الاختبار:',
        examFilterPlaceholder: 'اختر الاختبار',
        searchLabel: 'بحث:',
        searchPlaceholder: 'ابحث باسم الطالب أو الاختبار',
        emptyText: 'لا توجد نتائج اختبارات',
        emptyButtonText: 'رفع نتائج اختبار'
    },
    examResultsToastMsgConst: {
        uploadSuccessMsg: 'تم رفع نتائج الاختبار بنجاح',
        uploadErrorMsg: 'فشل في رفع نتائج الاختبار',
        deleteSuccessMsg: 'تم حذف النتيجة بنجاح',
        deleteErrorMsg: 'فشل في حذف النتيجة',
        downloadErrorMsg: 'فشل في تحميل النتيجة',
        autoSubmitSuccessMsg: 'تم حفظ نتائج الاختبار بنجاح',
        autoSubmitErrorMsg: 'حدث خطأ في حفظ نتائج الاختبار'
    },
    deleteExamResultModelConst: {
        deletePopUpTitle: 'تأكيد حذف النتيجة',
        deletePopUpText: 'متأكد انك تبي تحذف نتيجة الاختبار؟',
        deleteBtnText: 'تأكيد الحذف',
        cancelBtnText: 'تراجع'
    },
    examTerminationsConst: {
        terminationsTabTitle: 'سجلات انتهاء الاختبارات',
        terminationReasonLabel: 'سبب الانتهاء',
        distractionStrikesLabel: 'عدد التحذيرات',
        totalDistractionEventsLabel: 'عدد أحداث التشتيت',
        distractionTypesLabel: 'أنواع التشتيت',
        timeToTerminationLabel: 'وقت الانتهاء',
        terminationTimestampLabel: 'تاريخ الانتهاء',
        viewTerminationDetailsTitle: 'عرض تفاصيل التشتيت',
        deleteTerminationTitle: 'حذف سجل الانتهاء',
        noTerminationsText: 'لا توجد سجلات انتهاء اختبارات',
        terminationSearchPlaceholder: 'ابحث باسم الطالب أو الاختبار أو سبب الانتهاء',
        deleteTerminationConfirmTitle: 'تأكيد حذف سجل الانتهاء',
        deleteTerminationConfirmText: 'متأكد انك تبي تحذف سجل انتهاء الاختبار؟',
        deleteTerminationSuccessMsg: 'تم حذف سجل الانتهاء بنجاح',
        deleteTerminationErrorMsg: 'فشل في حذف سجل الانتهاء',
        fetchTerminationsErrorMsg: 'فشل في جلب سجلات انتهاء الاختبارات'
    }
} 