export const GET_PURCHASE_ORDER_LIST = 'GET_PURCHASE_ORDER_LIST'
export const GET_ENROLLED_COURSE_USER_LIST = 'GET_ENROLLED_COURSE_USER_LIST'
export const GET_ALL_COURSELIST_BY_INSTRUCTOR = 'GET_ALL_COURSELIST_BY_INSTRUCTOR'
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA'
